### PR TITLE
April2019 kiran v2 119 sum master rebase

### PR DESCRIPTION
**Pull request by kirandwarkan**
Upgraded / rebased against tagged 2.119 fastlane release

### CODE REVIEW

**Comment by kirandwarkan** [comment]
@jgale @rziehl Review and merge.

**Comment by jgale** [comment]
I'm no Git expert, but should our commit be on top, like the newest one? It shows it at the bottom when I look at the list of commits

**Comment by kirandwarkan** [comment]
I think the above history is an inline comment because I referenced my first PR that had merge conflicts, and that's why it looks backwards.

Screen Shot 2019-04-09 at 11 23 51 AM

Screen Shot 2019-04-09 at 11 24 06 AM

**Comment by rziehl** [comment]
lgtm 👍

**Pull request closed without merging**
